--test 1: simple test
--SELECT * FROM ACTOR;

--test 2: get all actors that haven't been dummied out
--SELECT ACTOR_NAME FROM ACTOR WHERE (ACTOR_NAME IS NOT "Dummy") ORDER BY ACTOR_NAME DESC; --we don't want to see the dummied out actor

--test 3: 
--SELECT ACTOR_NAME, HIT_POINTS, SKILL_POINTS FROM ACTOR LEFT JOIN STATUS ON ACTOR.ACTOR_STATUS = STATUS.COMBATANT;

--test 4 (demo): new class, new equipment, make a new actor, show it

INSERT INTO JOB_CLASS VALUES (4, "Ranger", "High movement");
INSERT INTO EQUIPMENT VALUES (4, "Bow and Arrows", "Weapon", 30, "DEX + 5");
INSERT INTO INVENTORY VALUES (4, 2, 1);
INSERT INTO SKILL VALUES (5, "Aim", "Increases accuracy", 0);
INSERT INTO SKILL_POOL VALUES (5, 1, 5, NULL, NULL);
INSERT INTO STATUS VALUES (5, 5, 5, 9, 9, 4, 14, 7);
INSERT INTO ACTOR VALUES (4, "Ike", 4, 4, 5, 5, 4);
SELECT ACTOR_NAME, STRENGTH, VITALITY, DEXTERITY, AGILITY, INTELLIGENCE FROM ACTOR LEFT JOIN STATUS
	ON ACTOR.ACTOR_STATUS = STATUS.COMBATANT;
