DELETE FROM ACTOR;
DELETE FROM ENEMY;
DELETE FROM EQUIPMENT;
DELETE FROM INVENTORY;
DELETE FROM ITEM;
DELETE FROM SKILL_POOL;
DELETE FROM SKILL;
DELETE FROM STATUS;
DELETE FROM JOB_CLASS;

INSERT INTO JOB_CLASS VALUES (1, "Fighter", "Physical attacker");
INSERT INTO JOB_CLASS VALUES (2, "Wizard", "Spellcaster");
INSERT INTO JOB_CLASS VALUES (3, "Cleric", "Healer and support");

INSERT INTO EQUIPMENT VALUES (1, "Sword", "Weapon", 50, "STR + 3, DEX + 3");
INSERT INTO EQUIPMENT VALUES (2, "Staff", "Weapon", 30, "INT + 3");
INSERT INTO EQUIPMENT VALUES (3, "Mace", "Weapon", 30, "STR + 5");

INSERT INTO ITEM VALUES (1, "Potion", "Consumable", 10, "Recover 50 HP");
INSERT INTO ITEM VALUES (2, "Dungeon Key", "Key Item", 0, "Opens locked doors");
INSERT INTO ITEM VALUES (3, "Elixir", "Consumable", 100, "Recover 300 HP");

INSERT INTO INVENTORY VALUES (1, 2, 4);
INSERT INTO INVENTORY VALUES (2, 1, 1);
INSERT INTO INVENTORY VALUES (3, 3, 5);
INSERT INTO INVENTORY VALUES (50, 1, 4);
INSERT INTO INVENTORY VALUES (51, 1, 2);
INSERT INTO INVENTORY VALUES (52, 1, 1);

INSERT INTO SKILL VALUES (1, "Double Attack", "Hit the target twice", 2);
INSERT INTO SKILL VALUES (2, "Fireball", "Shoot a ball of fire", 5);
INSERT INTO SKILL VALUES (3, "Heal", "Target recovers 50 HP", 2);
INSERT INTO SKILL VALUES (4, "Lock Picking", "Opens locked doors and treasure chests", 1);

INSERT INTO SKILL_POOL VALUES (1, 1, 2, 3, 4);
INSERT INTO SKILL_POOL VALUES (2, 1, 3, NULL, NULL);
INSERT INTO SKILL_POOL VALUES (3, 2, 3, NULL, NULL);
INSERT INTO SKILL_POOL VALUES (50, NULL, NULL, NULL, NULL);
INSERT INTO SKILL_POOL VALUES (51, 1, NULL, NULL, NULL);
INSERT INTO SKILL_POOL VALUES (52, 1, 2, 3, NULL);

INSERT INTO STATUS VALUES (1, 8, 8, 5, 4, 2, 15, 5);
INSERT INTO STATUS VALUES (2, 10, 5, 6, 5, 1, 20, 3);
INSERT INTO STATUS VALUES (3, 3, 3, 3, 5, 12, 11, 10);
INSERT INTO STATUS VALUES (50, 3, 2, 5, 3, 1, 5, 0);
INSERT INTO STATUS VALUES (51, 8, 10, 8, 5, 1, 12, 1);
INSERT INTO STATUS VALUES (52, 22, 19, 9, 4, 22, 30, 5);

INSERT INTO ENEMY VALUES (1, "Goblin", 50, 50, 50);
INSERT INTO ENEMY VALUES (2, "Wight", 51, 51, 51);
INSERT INTO ENEMY VALUES (3, "Demon", 52, 52, 52);

INSERT INTO ACTOR VALUES (1, "Dummy", 1, 1, 1, 1, 1);
INSERT INTO ACTOR VALUES (2, "Adam", 1, 2, 2, 2, 2);
INSERT INTO ACTOR VALUES (3, "Ben", 2, 3, 3, 3, 3);
